yum_packages:
  - { name: tmux }
  - { name: python2-pip }
  - { name: python3-pip }
  - { name: dnsmasq }
  - { name: bind-utils }

homebrew_packages:
  - { name: ghq }
  - { name: peco }
  - { name: zsh-completion }
  - { name: anyenv }
  - { name: exa }
  - { name: bat }
  - { name: procs }
#  - { name: fd }
#  - { name: sd }
#  - { name: ripgrep }
#  - { name: tokei }
  - { name: tflint }
  - { name: terraformer }
  - { name: tfsec }
  - { name: direnv }
  - { name: jsonnet }
  - { name: pv }

pip_packages:
  - { name: docker-compose }
  - { name: fabric }
  - { name: ansible-lint }
#  - { name: heroku }
