---
# refs https://www.bonusbits.com/wiki/HowTo:Install_IntelliJ_IDEA_on_Amazon_Linux_Workspace

- name: Download IntelliJ IDEA
  shell: "wget https://download.jetbrains.com/idea/ideaIU-{{idea_version}}.tar.gz -P $HOME/Downloads"

- name: Make directory for Applications/idea
  shell: "mkdir -p $HOME/Applications/idea"

- name: Extract downloaded Archive
  shell: "tar -xzf $HOME/Downloads/ideaIU-{{idea_version}}.tar.gz --strip-components 1 -C $HOME/Applications/idea"


# refs https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
# 「外部ファイルの変更同期は遅い可能性があります」の対処
- name: Set /etc/sysctl.d/idea.conf
  copy :
    src: etc/sysctl.d/idea.conf
    dest: /etc/sysctl.d/idea.conf
    owner: root
    group: root
    mode: 0666
    backup: yes
  become: yes

- name: Apply the /etc/sysctl.d/idea.conf change
  shell: "sysctl -p --system"
  become: yes
