---
- set_fact:
    ansible_facts:
      pkg_mgr: yum

# yum
- name: Install/Upgrade yum packages
  yum: name={{ item.name }} state={{ item.state|default('latest') }}
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python2
  with_items: "{{ yum_packages }}"

## amazon-linux-extras
#- name: Install amazon-linux-extras packages
#  shell: "amazon-linux-extras install {{ item.topic }}"
#  become: yes
#  vars:
#    ansible_python_interpreter: /usr/bin/python2
#  with_items: "{{ extra_packages }}"

# linuxbrew
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install/Upgrade Homebrew packages
  homebrew: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: "{{ homebrew_packages }}"
  register: brew_result

- name: Make directory for Brew Info
  file: path=brew_info state=directory

- name: Log Brew Info
  shell: |
    brew info {{ item | basename }} > brew_info/{{ item | basename }}
  with_items: "{{ brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list }}"
