---
# refs
# - https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/install-cliv2-linux.html#cliv2-linux-remove
# - https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/install-linux.html

- name: Download AWS CLI v2 package
  shell: "curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip"
  become: yes

- name: Extract downloaded Archive
  shell: "unzip /tmp/awscliv2.zip -d /tmp"
  become: yes

- name: Execute AWS CLI v2 installer
  shell: "/tmp/aws/install"
  become: yes
